name: CD
on: 
  push:
    branches: [ main ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: deploy using ssh
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/jawiriyah.malasngoding.uno/test2
          git pull origin main
          git status
